steps:
 # build the container image
 - name: "gcr.io/cloud-builders/docker"
   args: ["build", "-t", "gcr.io/runsclourtest/frontpy", "/pruebascloudrun"]
 # push the container image to Container Registry
 - name: "gcr.io/cloud-builders/docker"
   args: ["push", "gcr.io/runsclourtest/frontpy"]
 # Deploy container image to Cloud Run
 - name: "gcr.io/cloud-builders/frontpy"
   args: 
   - "run"
   - "deploy"
   - "--allow-unauthenticated"
   - "frontpy"
   - "--image"
   - "gcr.io/runsclourtest/frontpy"
   - "--region"
   - "us-central1"
   - "--platform"
   - "managed"
   - "--port"
   - "4200"
images:
- gcr.io/runsclourtest/frontpy 
